### ISSUE TITLE
Domain Knowledge

### ISSUE THREAD

**Issue by fujistoo** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#14]
Hey! You've mentioned quite a few times "domain expert knowledge" in the paper, but you never mentioned anything about where exactly it came from, or how you filtered down to these prompts. Would you mind shedding some light onto this part?

**Comment by caoyunkang** [comment]
Hi! Typically, experts could easily introduce some descriptions of the potential anomalies, including anomaly types, anomaly properties, etc. In our implementation, we play the role of experts ourselves. In specific, we developed those prompts according to the given anomaly types and given images. We suggest that some pre-trained caption models could be also used to get more in-context descriptions rather than human descriptions.
